_target_: app.model.TorchHub
backbone:
  _target_: timm.create_model
  model_name: resnet101
  pretrained: true
  num_classes: ${num_classes:${data.path},${data.label}}
label: ${data.label}
num_classes: ${num_classes:${data.path},${data.label}}
class_names: ${class_names:${data.path},${data.label}}
loss:
  _target_: torch.nn.CrossEntropyLoss
optimizer:
  _partial_: true
  _target_: torch.optim.AdamW
  # lr: 1e-3
  # momentum: 0.9
  # nesterov: true
# lr_scheduler:
#   _target_: torch.optim.lr_scheduler.LinearLR
#   _partial_: true
#   start_factor: 0.3333333333333333
#   total_iters: 5
train_metrics:
  accuracy:
    _target_: torchmetrics.Accuracy
    task: multiclass
    num_classes: ${model.num_classes}
  macro_accuracy:
    _target_: torchmetrics.Accuracy
    task: multiclass
    num_classes: ${model.num_classes}
    average: macro
test_metrics: ${model.train_metrics}
